version: '3.8'
services:
  web:
    image: stinov21/clumsy-tracker:latest
    expose:
      - "8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - web


  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  certbot-etc:
  certbot-www:

configs:
  nginx_conf:
    content: |
      events {
          worker_connections 1024;
      }
      http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
          sendfile on;
          keepalive_timeout 65;
          server {
              listen 80;
              server_name rens-clumsyness.help www.rens-clumsyness.help;
              location /.well-known/acme-challenge/ {
                  root /var/www/certbot;
              }
              location / {
                  return 301 https://$$host$$request_uri;
              }
          }
          server {
              listen 443 ssl;
              server_name rens-clumsyness.help www.rens-clumsyness.help;
              ssl_certificate /etc/letsencrypt/live/rens-clumsyness.help/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/rens-clumsyness.help/privkey.pem;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers HIGH:!aNULL:!MD5;
              location / {
                  proxy_pass http://web:8000;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
              }
          }
      }