# Generated by Django 4.2.23 on 2025-08-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(default='Ren', max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('clumsy_level', models.IntegerField(choices=[(1, 'Minor'), (2, 'Noticeable'), (3, 'Major'), (4, 'Legendary')])),
            ],
        ),
    ]
