# Generated by Django 4.2.23 on 2025-08-03 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
